Golang partitialy implemented
KarasssDev/golang-interpreter pull request #1
Opened 2022-04-27 13:56 UTC by KarasssDev

2022-04-27 17:08 UTC, Kakadu requested changes
Репортинг ошибок -- жестяная жесть

2022-04-27 17:08 UTC, Kakadu commented on src/Ast.hs
> +    | VChan
Интересно, почему каналы без аргументов. Он один?

2022-04-27 17:08 UTC, Kakadu commented on src/Ast.hs
> +    _ -> undefined
мерзость

2022-04-27 17:08 UTC, Kakadu commented on src/Ast.hs
> +    | GoFuncCall Id [GoExpr]
Если функции начнут возвращать функции, то тут будет скорее всего не Id

2022-04-27 17:08 UTC, Kakadu commented on src/Ast.hs
> +    | EmptyCondition
Что это? Вообще, лучше в комментах писать кусочек кода, который примерно соответствует конструктору AST

2022-04-27 17:08 UTC, Kakadu commented on src/Ast.hs
> +    | SetByInd Id GoExpr GoExpr
Замечание, аналогичное функциям

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/BaseFunc.hs
> +  x == y = errorUnexpectedTypes x y "==" "t" "t"
Правильно, чтобы интерпретатор завершался корректно и выдавал ошибку в интерпретируемой программе, а не громко падал

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/BaseFunc.hs
> +  x == y = errorUnexpectedTypes x y "==" "t" "t"
Зашквар

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Errors.hs
> +showValueType _ = undefined
ubdefined надо выпилить. Везде

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Interpreter.hs
> +typeCheck v t f = if eq v t then () else f
Это какая-то жесть

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Interpreter.hs
> +    _                        -> undefined -- видимо должен поймать парсер
Вроде как должен был поймать тайпчекер...

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +getRVarValue (t, v, rt) = v
А он не орал ворнингом про неиспользуемые переменные?
Если не орал, то их надо включить. Вроде как lexi_lambda писала правильный список дефолтных ворнингов

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +  Nothing -> lookupVar id xs
Охренительный выбор называть это id

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    scs = scopes (head (frameStack r) emptyFrame) ++ [scope r]
там точно не получится без добавления в конец?

2022-04-27 17:08 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    helper []     p l = undefined
Стрёмно

2022-04-27 17:55 UTC, KarasssDev commented on src/Ast.hs
> +    | VChan
Нет горутин -> пока о каналах не думал, там будет его id по идее

2022-04-27 17:58 UTC, KarasssDev commented on src/Ast.hs
> +    _ -> undefined
Насколько я понимаю undefined маркирует отсутстивие релизации. Кажется пока для остальных паттернов нет реализации тут должен быть undefined

2022-04-27 17:59 UTC, KarasssDev commented on src/Ast.hs
> +    | GoFuncCall Id [GoExpr]
А почему?

2022-04-27 17:59 UTC, KarasssDev commented on src/Ast.hs
> +    | EmptyCondition
добавлю комменты

2022-04-27 18:00 UTC, KarasssDev commented on src/interpreter/BaseFunc.hs
> +  x == y = errorUnexpectedTypes x y "==" "t" "t"
а что знакчит корректно на некорректной программе?

2022-04-27 18:01 UTC, KarasssDev commented on src/interpreter/Interpreter.hs
> +typeCheck v t f = if eq v t then () else f
Согласен, пофикшу

2022-04-27 18:01 UTC, KarasssDev commented on src/interpreter/Interpreter.hs
> +    _                        -> undefined -- видимо должен поймать парсер
да, тут будет тайпчек, коммент устарел

2022-04-27 18:02 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +getRVarValue (t, v, rt) = v
Вроде не орал, проверю

2022-04-27 18:03 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +  Nothing -> lookupVar id xs
не очень понимаю что не так?

2022-04-27 18:03 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +    scs = scopes (head (frameStack r) emptyFrame) ++ [scope r]
получится, так короче код просто

2022-04-27 18:12 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +    helper []     p l = undefined
Про undefined писал выше, замечания которые буду коммитами исправлять самому закрывать?

2022-04-27 18:47 UTC, Kakadu commented on src/Ast.hs
> +    | GoFuncCall Id [GoExpr]
Потому что оно не впихнется в Ваше ast

2022-04-27 18:49 UTC, Kakadu commented on src/interpreter/BaseFunc.hs
> +  x == y = errorUnexpectedTypes x y "==" "t" "t"
Это и значит)

2022-04-27 18:49 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +getRVarValue (t, v, rt) = v
Если не орёт, их надо включить

2022-04-27 18:49 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +  Nothing -> lookupVar id xs
Такая стандартная функция есть

2022-04-27 18:50 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    scs = scopes (head (frameStack r) emptyFrame) ++ [scope r]
Да, коротенький тормозной гавнокод

2022-04-27 18:50 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    helper []     p l = undefined
Если уверены, что всё поняли правильно -- закрывайте

2022-04-27 21:01 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +  Nothing -> lookupVar id xs
Справедливо

2022-04-28 09:54 UTC, Kakadu commented on src/Ast.hs
> +    | GoFuncCall Id [GoExpr]
`f(1)(2)`

2022-05-03 14:32 UTC, KarasssDev commented
> Репортинг ошибок -- жестяная жесть

2022-05-03 15:11 UTC, Kakadu commented on src/interpreter/Types.hs
> +getArrayElemType _ = error "must call only for arrays" -- fix me
Точно все замечания пофиксили?

2022-05-03 15:12 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +      Nothing  -> throwError internalErrorEmptyFrameStack
Помэтчить голову списка можно было бы и попроще

2022-05-03 15:14 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +      putAll xs
Там не было стандартной функции где-нить рядом с Traversable?

2022-05-03 15:15 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    Nothing -> throwError internalErrorEmptyFrameStack
Снова про голову списка.

2022-05-03 15:15 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    Nothing -> throwError internalErrorEmptyFrameStack
И везде тоже

2022-05-03 15:18 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    Nothing   -> throwError internalErrorEmptyFrameStack
!!!!!

2022-05-03 15:19 UTC, Kakadu commented on src/interpreter/Runtime.hs
> +    Nothing         -> error "fix me"
!!!

2022-05-03 15:21 UTC, KarasssDev commented on src/interpreter/Types.hs
> +getArrayElemType _ = error "must call only for arrays" -- fix me
видимо не точно

2022-05-03 15:21 UTC, KarasssDev commented on src/interpreter/Types.hs
> +getArrayElemType _ = error "must call only for arrays" -- fix me
сейчас исправлю

2022-05-03 15:24 UTC, Kakadu commented on src/interpreter/Interpreter.hs
> +    _         -> unexpectedInternalError -- тут точно должен поймать парсер
Говнокод detected

2022-05-03 15:29 UTC, Kakadu commented
Что-то я не вижу ни включенных ворнингов https://lexi-lambda.github.io/blog/2018/02/10/an-opinionated-guide-to-haskell-in-2018/

Ни горутин

2022-05-03 15:36 UTC, KarasssDev commented on src/interpreter/Runtime.hs
> +    Nothing   -> throwError internalErrorEmptyFrameStack
а что тут не так?

2022-05-03 17:05 UTC, Kakadu commented on src/interpreter/Interpreter.hs
> +          evalStatement (Block xs)
Тут тоже наверное какой-нибдуь traversde есть

2022-05-03 17:16 UTC, KarasssDev commented on src/interpreter/Interpreter.hs
> +          evalStatement (Block xs)
тут оставшаяся чать обратно в Block заворачивается, так что стандартные не подойдут

2022-05-13 12:40 UTC, Kakadu approved these changes
Будем считать, что это С

2022-05-13 12:49 UTC, merged